# Generated by Django 2.2 on 2020-10-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Este es un texto de descripcion, donde se detalla las caracteristicas del producto...'),
            preserve_default=False,
        ),
    ]
